POST http://localhost:3333/videos
Content-Type: application/json


{
    "title": "Js Video",
    "description":"Java video",
    "duration": 190

}


###

GET http://localhost:3333/videos


###

PUT http://localhost:3333/videos/2e50e204-66fc-47f1-8257-b2abfba97836
Content-Type: application/json

{
    "title": "React video",
    "description": "React video",
    "duration": 120
}

###


###

DELETE http://localhost:3333/videos/2e50e204-66fc-47f1-8257-b2abfba97836
